### ISSUE TITLE
Test cases are missing

### ISSUE THREAD

**Issue by Maha-Shawky** [bassant147/reading-charts#1]
The 2 test cases in the assignment not covered:

- Chart is added successfully to the dashboard view after pressing add chart.
- If something went wrong and the api responded with 500 status code, an alert should be displayed with “Something wrong happened, please try again.
Please Use any end to end testing framework (testcafe, cypress or anything else) to cover them

**Comment by bassant147** [comment]
I would love the opportunity to add these test cases. Can I get an
extension?

**Comment by bassant147** [comment]
Hello Maha,
Can you please tell me if these are the tests you asked for? and if something is missing, I'd love to know what I got wrong.
